### ISSUE TITLE
Feature: User can search for images for a specific planet

### ISSUE THREAD

**Issue by Hagop420** [Hagop420/Spaceaholics#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 

🖼️ Wireframes

![Image 11-28-23 at 10 19 PM](https://github.com/Hagop420/ajax-project/assets/81959688/bcc44be3-984f-4f57-af92-f8f5ae7ddb40)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In index.html create a form tag
- [x] Inside the html form element create a single input for the planets
- [x] Inside of the form element create a search button and give the icon a font awesome class of .fa-solid fa-magnifying-glass
- [x] Style the form using CSS/Bootstrap
- [x] Inside of your main.js file create a new XMLHttpRequest
- [x] Call the XMLHttpRequest to the images and videos library
- [x] Add an event for the magnifying glass when the user clicks
- [x] Create a condition if the input matches the keywords for the XMLHttpRequest
- [x] If it matches create an image element and parse the specified planet image in the DOM.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
