### ISSUE TITLE
Feature: User can delete an issue

### ISSUE THREAD

**Issue by Hagop420** [Hagop420/Spaceaholics#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![Image 11-29-23 at 9 54 PM](https://github.com/Hagop420/Spaceaholics/assets/81959688/6de54590-8ea4-492b-9dab-e6401dde3ac9)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ...Inside of main.js define a toggleEntires() function 
- [ ] Inside the function listen for the data.entries data if they have a length of 0 give the error message a block if not hide it
- [ ]Inside the modal create a for loop which will target every single li element 
- listen for if the list items are equal to the current itteration delete the list item
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
